dataset: 'cifar'
batch_size: 64
num_classes: 10
upper_bound: 3.0
evaluate_upper_bound: 1.0
alpha: 0.2
model_path_template: './out/CIFAR10/models/cifar10_%s.pt'
noise_path_template: './out/CIFAR10/case1/models/train_noise_epoch_%d.pt'
img_path_template: './out/CIFAR10/case1/images'
noise_path: './out/CIFAR10/case1/models/train_noise_epoch_19.pt'
# sort: 0 1 2 3 4 5 -> 0 2 4 1 3 5
model_indexs:
  - 0
  - 7
  - 9
  - 18
  - 32
  - 1
  - 8
  - 12
  - 21
  - 34
