dataset: 'cifar100'
batch_size: 64
num_classes: 100
model_path_template: './out/CIFAR100/models/cifar100_%s.pt'
model_indexs:
  - 0
  - 1
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 18
  - 19
  - 20
  - 21
  - 22
  - 24
  - 27
  - 32
  - 33
  - 34
  - 35
