dataset: 'cifar'
batch_size: 64
num_classes: 10
upper_bound: 3.0
evaluate_upper_bound: 1.0
alpha: 0.2
model_path_template: './out/CIFAR10/models/cifar10_%s.pt'
noise_path_template: './out/CIFAR10/case5/models/train_noise_epoch_%d.pt'
img_path_template: './out/CIFAR10/case5/images'
noise_path: './out/CIFAR10/case5/models/train_noise_epoch_19.pt'
model_indexs:
  - 0
  - 1
  - 7
  - 8
  - 9
  - 12
  - 18
  - 21
  - 32
  - 34
# drop resnet20 and vgg16
dropped_model_indexs:
  - 18
  - 34