dataset: 'cifar'
batch_size: 64
num_classes: 10
upper_bound: 3.0
evaluate_upper_bound: 1.0
alpha: 0.2
model_path_template: './out/CIFAR10/models/cifar10_%s.pt'
noise_path_template: './out/CIFAR10/models/train_noise_epoch_%d.pt'
img_path_template: './out/CIFAR10/images'
noise_path: './out/CIFAR10/models/train_noise_epoch_19.pt'
model_indexs:
  - 18
  - 19
  - 20
  - 21
  - 32
  - 33
  - 34
  - 35
  # - 0
  # - 1
  # - 7
  # - 8
  # - 9
  # - 12
  # - 18
  # - 21
  # - 32
  # - 34
